
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - exporter.thrawny.com
  resources:
  - objectexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exporter.thrawny.com
  resources:
  - objectexporters/status
  verbs:
  - get
  - patch
  - update
