
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: objectexporters.exporter.thrawny.com
spec:
  group: exporter.thrawny.com
  names:
    kind: ObjectExporter
    listKind: ObjectExporterList
    plural: objectexporters
    singular: objectexporter
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ObjectExporter is the Schema for the objectexporters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ObjectExporterSpec defines the desired state of ObjectExporter
          properties:
            description:
              description: Description regroups information and metadata about an
                application.
              type: string
            identifier:
              description: Intruments is a list of time series specs that will be
                exported for the Resource Identifier
              items:
                description: InstrumentSpec configures a time
                properties:
                  additionalLabelsFromFields:
                    additionalProperties:
                      type: string
                    description: 'AdditionalLabelsFromFields is formatted as LabelName:'
                    type: object
                  name:
                    description: Name is the subresource being intrumented or tracked
                    type: string
                  type:
                    description: Type represents the time series metric type. https://prometheus.io/docs/concepts/metric_types/
                    type: string
                  unit:
                    description: UnitAggregation refers to how the Unit is being tracked.
                      _count or _total for sum,
                    type: string
                  valueJSONPath:
                    description: ValueJSONPath sets the field or strategy for determining
                      the time series value
                    type: string
                type: object
              type: array
          type: object
        status:
          description: ObjectExporterStatus defines the observed state of ObjectExporter
          properties:
            exportedTimeSeries:
              description: ExportedTimeSeries is a preview of the time series exported
              items:
                type: string
              type: array
            instrumentedResourceCount:
              description: A count of objects being counted
              format: int64
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
